# Generated by Django 2.0 on 2018-09-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='data',
            new_name='rule',
        ),
    ]
