# Generated by Django 2.0 on 2018-09-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180927_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Rules',
        ),
    ]
